### PR TITLE
Added rocket runtime.

### PR DESCRIPTION
**Pull request by yifan-gu**
@bcwaldon @sym3tri I cleaned up the code, addressed all comments I think. PTAL.

### CODE REVIEW

**Comment by bcwaldon** [comment]
@yifan-gu 
1. Does this PR now supersede https://github.com/coreos/kubernetes/pull/2?
2. Please separate out your godep changes into a separate commit.

**Comment by yifan-gu** [comment]
@bcwaldon 
1. Yes.
2. I splitted into 3 commits, hope that makes sense.

**Comment by yifan-gu** [comment]
@bcwaldon BTW, I created service files instead of symlinks under /etc/systemd/system, is that OK?? Not sure about the convention.

**Comment by yifan-gu** [comment]
Alright, I changed `/etc/systemd/system` to /`lib/systemd/system`, since `docker.service` is put in this dir.

**Comment by yifan-gu** [comment]
BTW, I found the git hook for k8s requires all files have the copyright of Google Inc. It yells at me when I change it to CoreOS Inc (though I 'ignore' it).

Will that cause any issue?
FYI:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hooks/boilerplate.sh

**Comment by yifan-gu** [comment]
Comments addressed (but in another WIP branch)
Going to move container.go under pkg/kubelet/container and add a fake runtime there.

**Comment by yifan-gu** [comment]
I feel like the RestartContainerInPod could be taken out of the interface.

**Comment by jonboulle** [comment]
@yifan-gu is there an updated version somewhere we should be reviewing?

**Comment by yifan-gu** [comment]
@jonboulle @bcwaldon Updated. I deleted all tests in kubelet_test.go, now I am adding them back.

Also adding tests for rocket's implementation for the interface.

**Comment by yifan-gu** [comment]
moved to #4

**Pull request closed without merging**
