### PR TITLE
V1.10.0 patchset

### PR DESCRIPTION
**Pull request by rphillips**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by colemickens** [comment]
Did your version regex merge upstream then?

**Review by colemickens — APPROVED** [review]

**Comment by rphillips** [comment]
sure did.

**Comment by antoineco** [comment]
Will future versions still be pushed to https://quay.io/repository/coreos/hyperkube? Asking because I don't see this release published on Quay.

**Comment by rphillips** [comment]
yes. I'm working on a build issue with the 1.10.0 release.

**Pull request merged**
