### PR TITLE
Add Calico IPAM plugin to manage pod IP addresses

### PR DESCRIPTION
**Pull request by brianredbeard**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

This contributes to resolution of #106. 

**Release note**:

```release-note
The Calico CNI mechanism needs both the calico plugin as well as the calico ip address management (IPAM) plugin to function sucessfully.  Previously the IPAM plugin was left out.
```

### CODE REVIEW

**Comment by aaronlevy** [comment]
cc @tomdee -- this seem reasonable to you?

**Comment by tomdee** [comment]
You should bump the Calico CNI plugin version to v1.8.3 at the same time.
Otherwise, the change looks fine.

also cc @heschlie

**Comment by brianredbeard** [comment]
Updated the Calico plugin version as well.

**Comment by heschlie** [comment]
LGTM

**Review by peebs — APPROVED** [review]
LGTM -- will be out in the next release either 1.6.5 or a point release on 1.6.4

**Pull request merged**
