### PR TITLE
V1.8.0-rc.1-patchset

### PR DESCRIPTION
**Pull request by squat**
Carries patches from v01.8.0-beta.1+coreos.0. Tests are passing.

cc @aaronlevy @s-urbaniak

### CODE REVIEW

**Review by s-urbaniak — APPROVED** [review]
LGTM

**Comment by s-urbaniak** [comment]
just for clarity: this carries mechanically the same patches as in https://github.com/coreos/kubernetes/pull/161 (v1.8.0-beta.1).

**Comment by squat** [comment]
@s-urbaniak I just bumped calico to v1.11.0. Re-running the tests.

**Review by s-urbaniak — APPROVED** [review]
ack, LGTM once green 👍

**Pull request merged**
