### PR TITLE
Add trusted compute code

### PR DESCRIPTION
**Pull request by mjg59**

### CODE REVIEW

**Comment by philips** [comment]
@mjg59 could the tpm-manager be in a separate container as a daemonset?

cc @aaronlevy

**Comment by mjg59** [comment]
@philips As long as it can hit the :8080 endpoint that's no problem

**Comment by aaronlevy** [comment]
@mjg59 it can hit the insecure endpoint as long as it is either run on the same host as api-server, or even could be a side-car container in the same pod.

But why does it need the insecure endpoint?

**Comment by mjg59** [comment]
@aaronlevy We need some mechanism to distinguish between requests that come from trusted sources (ie, tpm-manager) and everything else (eg, the nodes). The easiest way to do that is to just check whether something came from the insecure endpoint or an authenticated user - the alternative is that we need very strongly defined naming policy for users to key off.

**Comment by aaronlevy** [comment]
Tracking some offline discussion:
- Concern about assuming a request is "trusted" because it is unauthenticated (due to co-location of api-server) could be an issue for things like kubectl and dashboard making changes. We likely need to compartmentalize this differently (e.g. maybe by user / service account / etc).
- Discussion about carrying tpm-manager as part of this repository, when it could be an isolated project.
  - _If carried as part of this repo_, it doesn't need to vendor its own copy of k8s. However, it means we also likely need to carry its build process in this repo as well (e.g. dockerfile, etc).  Also there is question of tagging tpm-release manager releases independently of kubernetes releases -- which could make this repo somewhat complex (bugs / releases page / etc).
  - _If maintained as an independent project_, it would need to vendor its own copy of kubernetes (likely this repo), but would keep this tree somewhat cleaner, and potentially cleaner from an independent release cycle standpoint.

**Comment by mjg59** [comment]
One other option was to maintain it in the coreos/kubernetes repo, but as a separate branch

**Comment by philips** [comment]
cc @hongchaodeng @xiang90 see   24546ad for the TPR fix

**Comment by aaronlevy** [comment]
Closing this as this work is taking place in https://github.com/coreos/kubernetes/pull/43

**Pull request closed without merging**
