### PR TITLE
V1.8.2 patchset

### PR DESCRIPTION
**Pull request by squat**
Carries patches from v1.8.1. Dev tests are passing. Do we want to cherry-pick any other patches?

cc @s-urbaniak @aaronlevy @rphillips @ericchiang

### CODE REVIEW

**Comment by s-urbaniak** [comment]
as discussed OOB, I suggest to carry the same cni patches as in https://github.com/coreos/kubernetes/pull/174/files

**Comment by s-urbaniak** [comment]
in addition `modprobe` is still not included in the upstream 1.8.2 hyperkube image.

**Comment by squat** [comment]
@s-urbaniak PTAL again. currently testing

**Comment by brancz** [comment]
FWIW the memory/metrics leak seems to be fixed. I've been running the 1.8.2-dev image for a couple hours on my cluster and it seems to be stable metrics/memory amount.

**Review by s-urbaniak — APPROVED** [review]
LGTM 👍

**Pull request merged**
