### PR TITLE
Scheduler Optimization

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
@xiang90

**Comment by xiang90** [comment]
@hongchaodeng I think this is a correct direction. Now we are using the new interface with old implementation(podLister + systemModeler), right?

**Comment by hongchaodeng** [comment]
Right.
In fact, the PodLister is part of system modeler.

**Comment by xiang90** [comment]
@hongchaodeng Great! Let's try to finish this up next week and get some initial testing result. Then we can ask Huawei/redhat(whoever has interest in perf) guys to give it a test.

**Pull request closed without merging**
