### PR TITLE
regenerate files for 2018 year

### PR DESCRIPTION
**Pull request by rphillips**
**What this PR does / why we need it**: updates the year within the generated files. It can be removed when 1.8.7 gets released.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ericchiang** [comment]
Did the upstream PR not cherry pick correctly? https://github.com/kubernetes/kubernetes/pull/57767

**Comment by ericchiang** [comment]
Woops, I mean https://github.com/kubernetes/kubernetes/pull/57771

**Comment by rphillips** [comment]
@ericchiang fixed

**Review by ericchiang — APPROVED** [review]
lgtm, thanks!

**Comment by dghubble** [comment]
Do we really need to be doing this?

**Comment by rphillips** [comment]
@dghubble yes... The build errors with the linter because of the invalid year (2018). Looks like upstream is going to eventually remove the year within the linter.

**Comment by rphillips** [comment]
1.8.7 should have the patch to fix the build: https://github.com/kubernetes/kubernetes/pull/57771

**Comment by dghubble** [comment]
Ok

**Pull request merged**
